{% set version = "2.0.19" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rxode2parse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rxode2parse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rxode2parse/rxode2parse_{{ version }}.tar.gz
  sha256: 9d418a353d226beb453a1112767fcc4da6196da843180e0a9581da8321640307

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/tbb.dll'         # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.78.0.0
    - r-checkmate
    - r-crayon
    - r-data.table >=1.12.4
    - r-digest
    - r-dparser >=1.3.1_10
    - r-knitr
    - r-qs
    - r-rcpp >=1.0.8
    - r-rcppeigen >=0.3.3.9.2
    - r-rex
    - r-stanheaders >=2.21.0.7
    - r-symengine
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    #- r-bh >=1.78.0.0
    - r-checkmate
    - r-crayon
    - r-data.table >=1.12.4
    - r-digest
    - r-dparser >=1.3.1_10
    - r-knitr
    - r-qs
    - r-rcpp >=1.0.8
    - r-rcppeigen >=0.3.3.9.2
    - r-rex
    #- r-stanheaders >=2.21.0.7
    - r-symengine

test:
  commands:
    - $R -e "library('rxode2parse')"           # [not win]
    - "\"%R%\" -e \"library('rxode2parse')\""  # [win]

about:
  home: https://nlmixr2.github.io/rxode2parse/
  dev_url: https://github.com/nlmixr2/rxode2parse/
  license: GPL-3.0-or-later
  summary: Provides the parsing needed for 'rxode2' (Wang, Hallow and James (2016) <doi:10.1002/psp4.12052>). It also provides the 'stan' based advan linear compartment model solutions with gradients (Carpenter et al (2015), <arXiv:1509.07164>) needed in 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This split
    will reduce computational burden of recompiling 'rxode2'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
